services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"

  backend:
    build: ./server
    container_name: todo-backend
    ports:
      - "5001:5000"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
